import { HStack, VStack } from '@chakra-ui/react'
import InfoTooltip from 'components/InfoTooltip'
import { TooltipWithChildren } from 'components/TooltipWithChildren'

type Props = {
  multiplicator: string
  apr: string
  show: boolean
  incentivized: boolean
}

const Multiplicator = ({ multiplicator, apr, show, incentivized }: Props) => {
  if (!show) {
    return null
  }

  return (
    <VStack
      justifyContent="space-between"
      width="full"
      border="1px solid rgba(255, 255, 255, 0.1)"
      borderRadius="15px"
      p={4}
      pt={3.5}
      style={{ marginBottom: 50 }}
    >
      <HStack justifyContent="space-between" width="full">
        <TooltipWithChildren
          label="Multiplier"
          isHeading
          fontSize="16"
        >
          {'Factor by which your APR gets multiplied.'}
        </TooltipWithChildren>

        <TooltipWithChildren
          label={multiplicator}
          fontSize="16"
          showTooltip={false}
        />
      </HStack>
      <HStack justifyContent="space-between" width="full">
        <TooltipWithChildren
          label="Estimated APR"
          isHeading
          fontSize="16">
          {'Multiplier 0 is the base APR generated by fees. Multiplier 1 is the APR with incentives.\n' +
            'Above 1, the incentive APR is multiplied by the multiplier that increases up to 16 linearly, if you lock your tokens for 365 days.'
          }
        </TooltipWithChildren>
        <HStack>
          {incentivized && <InfoTooltip
            iconSize={3}
            description={
              'This pool is currently incentivized. The creator can clawback all unclaimed rewards at anytime. Claim them regularly.'
            }
          />}
          <TooltipWithChildren
            label={`${apr}%`}
            fontSize="16"
            showTooltip={false}
          />
        </HStack>
      </HStack>
    </VStack>
  )
}

export default Multiplicator
